GENERAL:
  run_mode: inference

EMBEDDER:
  class: SentenceEmbedder
  package: saturn.components.embeddings.embedding_models
  pretrained_name_or_abspath: keepitreal/vietnamese-sbert
  device: "cuda"
  TRAINER:
    triplets_data_path:
      - data/train_data/dummy/triples/triples_10.json
      - data/train_data/dummy/triples/triples_20.json
      - data/train_data/dummy/triples/triples_30.json
    model_save_path: models_test
    n_samples: 10
    batch_size: 128
    epochs: 300
    warmup_steps: 5000
    evaluation_steps: 2000
    weight_decay: 0.01
    max_grad_norm: 1.0
    use_amp: True
    save_best_model: True
    show_progress_bar: True
    checkpoint_path: models/checkpoints
    checkpoint_save_epoch: 50
    checkpoint_save_total_limit: 3
    device_name: 0

EVALUATION:
  type: "evaluation_pipeline"
  corpus_name_or_path: "data/eval-data/timi/v2.0.0/corpus.json"
  query_name_or_path: "data/eval-data/timi/v2.0.0/query.json"
  pretrained_name_or_abspath:
    - models/epoch-0
    - models/epoch-1
    - models/epoch-3
    - models/epoch-5
    - models/epoch-7
    - models/epoch-8
    - models/epoch-9
    - models/epoch-11
    - models/epoch-12
    - models/epoch-13
    - models/epoch-14
    - models/epoch-15
    - models/epoch-16
    - models/epoch-17
    - models/epoch-18
    - models/epoch-19
    - models/epoch-20
