GENERAL:
  device: cuda
  project: dummy
  version: v1.0.0
  is_warning_action: True
  output_data: assets
  output_model: models
  output_report: reports

  # Skipped signal
  skipped_gen_data: False
  skipped_training: False
  skipped_eval: True

DATA_GENERATION:
  data_dir: data/raw/dummy
  search_mode: bm25_embedder
  embedding_batch_size: 100
  neg_sim_batch_size: 10
  max_triple_per_file: 50
  max_sentence_repeated: 2
  EMBEDDER:
    cache_path: ./embedder_caches
    pretrained_name_or_abspath: timi-idol-keepitreal-vn-sbert-faq-9M-v1.0.0
#  COMBINER:


TRAINER:
  class: SBertSemanticSimilarity
  package: saturn.components.embeddings.embedding_models
  pretrained_name_or_abspath: keepitreal/vietnamese-sbert
  n_samples: 10
  batch_size: 256
  epochs: 20
  warmup_steps: 5000
  evaluation_steps: 2000
  weight_decay: 0.01
  max_grad_norm: 1.0
  use_amp: True
  save_best_model: True
  show_progress_bar: True
  checkpoint_save_epoch: 4
  checkpoint_save_total_limit: 10
  save_by_epoch: 4
#    resume_from_checkpoint: checkpoints/epoch-14/checkpoint.pt

EVALUATION:
  type: "evaluation_pipeline"
  corpus_name_or_path: "data/eval-data/dummy/corpus_docs.json"
  query_name_or_path: "data/eval-data/dummy/query_docs.json"
  pretrained_name_or_abspath:
    - models/dummy/v1.0.0/epoch-15

RELEASE:
  model_path: models
  pretrained_model: MiniLM-L12-H384-uncased
  data_size: 9M