DOC_STORE_INMEMORY = "inmemory"
DOC_STORE_ELASTICSEARCH = "elasticsearch"
RETRIEVER_EMBEDDING = "embedding"
RETRIEVER_ELASTICSEARCH = "elasticsearch"

DEFAULT_DOCSTORE_TYPES = [DOC_STORE_INMEMORY, DOC_STORE_ELASTICSEARCH]
DEFAULT_RETRIEVER_TYPES = [RETRIEVER_ELASTICSEARCH, RETRIEVER_EMBEDDING]
DEFAULT_FILE_TYPES = ['md', 'json']
