EVALUATION:
  type: "evaluation_pipeline"
  corpus_name_or_path: "assets/corpus.json"
  query_name_or_path: "assets/query.json"
  doc_store_name: ["memory"]
  model_name_or_path: ["fschool-distilbert-multilingual-faq-v8.0.0"]
  retriever_type: ["embedding"]
