GENERAL:
  run_mode: inference

EMBEDDER:
  class: QuadrupletEmbedder
  package: saturn.components.embeddings.embedding_models

  TRAINER:
    quadruplet_data_path:
      - data/train_data/dummy/quadruples/quadruples_30.json
    pretrained_model: sentence-transformers/all-MiniLM-L6-v2
    model_save_path: models/all-MiniLM-L6-v2_Test_quaruplet-loss
    n_samples: 10
    batch_size: 64
    epochs: 3
    warmup_steps: 5000
    evaluation_steps: 2000
    weight_decay: 0.01
    max_grad_norm: 1.0
    use_amp: True
    save_best_model: True
    show_progress_bar: True
    checkpoint_path: models/all-MiniLM-L6-v2_Test_quaruplet-loss/checkpoints
    checkpoint_save_epoch: 1
    checkpoint_save_total_limit: 2

EVALUATION:
  type: "evaluation_pipeline"
  corpus_name_or_path: "data/eval-data/dummy/corpus_docs.json"
  query_name_or_path: "data/eval-data/dummy/query_docs.json"
  model_name_or_path: [ "models/all-MiniLM-L6-v2_Test_quaruplet-loss" ]

