GENERAL:
  run_mode: inference

EMBEDDER:
  class: SentenceEmbedder
  package: saturn.components.embeddings.embedding_models
  model_name_or_path: microsoft/MiniLM-L12-H384-uncased
  gpu: 1
  TRAINER:
    triplets_data_path:
      - assets/timi/bm25_embedder/triples_2000000.json
      - assets/timi/bm25_embedder/triples_4000000.json
      - assets/timi/bm25_embedder/triples_6000000.json
      - assets/timi/bm25_embedder/triples_8000000.json
      - assets/timi/bm25_embedder/triples_8284471.json

    model_save_path: models
    n_samples: 10
    batch_size: 256
    epochs: 20
    warmup_steps: 5000
    evaluation_steps: 2000
    weight_decay: 0.01
    max_grad_norm: 1.0
    use_amp: True
    save_best_model: True
    show_progress_bar: True
    checkpoint_path: checkpoints
    checkpoint_save_epoch: 3
    checkpoint_save_total_limit: 10
    save_by_epoch: 1
#    resume_from_checkpoint: models/checkpoints/epoch-495/checkpoint.pt

EVALUATION:
  type: "evaluation_pipeline"
  corpus_name_or_path: "data/eval-data/timi/corpus.json"
  query_name_or_path: "data/eval-data/timi/query.json"
  model_name_or_path:
#    - distilbert-multilingual-faq-v3.2
#    - fschool-distilbert-multilingual-faq-v8.0.0
#    - timi-idol-paraphrase-multilingual-MiniLM-L12-v2-v.1.0.1
#    - khanhpd2/sbert_phobert_large_cosine_sim
    - models/checkpoints/epoch-11
    - models/checkpoints/epoch-14
    - models/checkpoints/epoch-17