GENERAL:
  run_mode: inference

EMBEDDER:
  class: SentenceEmbedder
  package: saturn.components.embeddings.embedding_models
  pretrained_name_or_abspath: keepitreal/vietnamese-sbert
  device: cuda:1
  TRAINER:
    triplets_data_path:
      - /home/haonv/workspaces/knowledge-retriever-data/assets/timi/bm25_embedder/triples_2000000.json
      - /home/haonv/workspaces/knowledge-retriever-data/assets/timi/bm25_embedder/triples_4000000.json
      - /home/haonv/workspaces/knowledge-retriever-data/assets/timi/bm25_embedder/triples_6000000.json
      - /home/haonv/workspaces/knowledge-retriever-data/assets/timi/bm25_embedder/triples_8000000.json
      - /home/haonv/workspaces/knowledge-retriever-data/assets/timi/bm25_embedder/triples_10000000.json
      - /home/haonv/workspaces/knowledge-retriever-data/assets/timi/bm25_embedder/triples_12000000.json
      - /home/haonv/workspaces/knowledge-retriever-data/assets/timi/bm25_embedder/triples_13144236.json

    model_save_path: models_ood
    n_samples: 10
    batch_size: 256
    epochs: 20
    warmup_steps: 5000
    evaluation_steps: 2000
    weight_decay: 0.01
    max_grad_norm: 1.0
    use_amp: True
    save_best_model: True
    show_progress_bar: True
    checkpoint_path: checkpoints_ood
    checkpoint_save_epoch: 3
    checkpoint_save_total_limit: 10
    save_by_epoch: 1
#    resume_from_checkpoint: checkpoints/epoch-14/checkpoint.pt

EVALUATION:
  type: "evaluation_pipeline"
  corpus_name_or_path: "data/eval-data/timi/v2.0.0/corpus.json"
  query_name_or_path: "data/eval-data/timi/v2.0.0/query.json"
  pretrained_name_or_abspath:
    - models_ood/epoch-0
    - models_ood/epoch-1
    - models_ood/epoch-2
    - models_ood/epoch-3
    - models_ood/epoch-4
#    - models_ood/epoch-5
#    - models_ood/epoch-7
#    - models_ood/epoch-8
#    - models_ood/epoch-9
#    - models_ood/epoch-11
#    - models_ood/epoch-12
#    - models_ood/epoch-13
#    - models_ood/epoch-14
#    - models_ood/epoch-15
#    - models_ood/epoch-16
#    - models_ood/epoch-17
#    - models_ood/epoch-18
#    - models_ood/epoch-19
#    - models_ood/epoch-20
